[package]
name = "WaterQualityTesting"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8", features = ["small_rng"] }
plotters = "0.3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "WaterQualityTesting"
path = "src/main.rs"